# ===========================================
# Docker Compose - Local Development Database
# ===========================================
# Only runs PostgreSQL for local development
# Run the Rust app locally with: systemfd --no-pid -s http::3000 -- cargo watch -x run
#
# Usage from project root: docker-compose -f docker/docker-compose.dev.yml up -d

services:
  # PostgreSQL Database for local development
  db:
    image: postgres:16.6
    env_file: 
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-rust_axum_api}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      # Optional: Add init scripts if needed
      # - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-rust_axum_api}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  dev_network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local 